# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'NASSDKDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

   # pod 'NASSDK','1.0.3'

   # pod 'ZFPlayer/ijkplayer', '~> 4.0'
   # pod 'ZFPlayer/ControlView', '~> 4.0'

end
