# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'NASSDKDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

   pod 'NASSDK','1.4.13'

   pod 'JLRoutes'
   pod 'ZFPlayer/ijkplayer', '~> 4.0'
   pod 'ZFPlayer/ControlView', '~> 4.0'
end


post_install do |installer|
    installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
               end
          end
   end
end 
